server:
  port: 8080
spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
    url: jdbc:mysql://47.106.126.84:3306/open_account?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: test
    password: 123456
mybatis:
  mapperLocations: classpath:/mapper/*.xml



